### ISSUE TITLE
Could there be an option to auto-update to the latest bedrock version?

### ISSUE THREAD

**Issue by datimson** [ich777/docker-minecraft-bedrock#1]

**Comment by ich777** [comment]
I will look into that, should be totally doable.
Is it enough that the container checks on every start/restart for updates?

**Comment by ich777** [comment]
@datimson now you can set the GAME_VERSION variable to 'latest' (without quotes), the container will check on every start/restart if there is a newer version available and update it.

**Comment by datimson** [comment]
Brilliant, thank you!
