### ISSUE TITLE
Can't access Web Console in latest version of chrome

### ISSUE THREAD

**Issue by jordankothe9** [ich777/docker-minecraft-bedrock#3]
The web console is blank in the most recent version of Chrome. When the docker container shuts down, the console/white screen will display "disconnected".

Works fine in Firefox

Using the latest version of chrome, firefox, and the docker image

**Comment by ich777** [comment]
Do you have any addons/extensions like AdBlocking installed?

I have to look into that because I don't use Chrome at all. Maybe this is a bug with `gotty`.

**Comment by ich777** [comment]
Seems to work fine here:
![grafik](https://github.com/ich777/docker-minecraft-bedrock/assets/28066518/07a35178-ec61-447f-b15f-39da06714840)

**Comment by jordankothe9** [comment]
Opening in Incognito seems to work, but I've not been able to identify which extension is causing the problem. I do use adblock and I've disabled it completely I still can't connect to the console. Also cleared cookies and cache. I'm continuing to troubleshoot. If I find anything I'll update here for anyone else running into the problem.

**Comment by jordankothe9** [comment]
Looks like The Browser Extension "Dark Mode" causes the console to not load even if it's disabled. After completely removing from chrome the console loads perfect.

https://chromewebstore.google.com/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj?hl=en-US&utm_source=ext_sidebar

**Comment by ich777** [comment]
Glad that you've figured it out and nice to hear that everything is working again!
